	public void testBug80194string2() throws CoreException, JavaModelException {
		assertNotNull("Problem in tests processing", workingCopies);
		assertEquals("Problem in tests processing", 1, workingCopies.length);
		search("doSomething(Map<String,Object>)", METHOD, ALL_OCCURRENCES);
		assertSearchResults(
			"src/b80194/Test.java void b80194.Test.callDoSomething() [doSomething(map)] EXACT_MATCH\n" + 
			"src/b80194/Test.java void b80194.Test.doSomething(Map<String,Object>) [doSomething] EXACT_MATCH"
		);
		// keep working copies for next test
		discard = false;
	}

