    public Throwable getException() {
        return getCause();
    }

