	abstract void foo2() throws Exception;

