	// null analysis - try/catch
	// TODO (maxime) fix
	public void _test0178_try_catch() {
		this.runNegativeTest(
			new String[] {
				"X.java",
				"public class X {\n" + 
				"	 boolean dummy;\n" + 
				"	 void foo() {\n" + 
				"		 Object o = new Object();\n" + 
				"		 try {\n" + 
				"			 if (dummy) {\n" + 
				"			   System.out.print(0);\n" + // may thow RuntimeException 
				"			   o = null;\n" + 
				"			   throw new LocalException();\n" + 
				"			 }\n" + 
				"		 }\n" + 
				"		 catch (LocalException e) {\n" + // doesn't catch RuntimeException
				"			 o.toString();\n" +
				 	// complain: know o is null despite the lack of definite assignment
				"		 }\n" + 
				"	 }\n" + 
				"	 class LocalException extends Exception {\n" + 
				"		 private static final long serialVersionUID = 1L;\n" + 
				"	 }\n" + 
				"}\n"},
			"WARN"
		);
	}

